FROM node:alpine

RUN apk add --no-cache \
    chromium \
    nss \
    freetype \
    freetype-dev \
    harfbuzz \
    ca-certificates \
    ttf-freefont \
    ghostscript \
    graphicsmagick

COPY package*.json /app/
WORKDIR /app
RUN npm ci --omit=dev