apiVersion: batch/v1
kind: Job
metadata:
  name: backfill-report-runs
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: backfill
          image: ghcr.io/klimatbyran/garbo
          imagePullPolicy: Always
          command: ['npm', 'run', 'backfill:report-runs']
          envFrom:
            - secretRef:
                name: env
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: postgres-password
