import { DiscordQueue } from './lib/DiscordQueue'

// Queue names as constants
export const QUEUE_NAMES = {
  PARSE_PDF: 'parsePdf',
  DOCLING_PARSE_PDF: 'doclingParsePDF',
  NLM_EXTRACT_TABLES: 'nlmExtractTables',
  INDEX_MARKDOWN: 'indexMarkdown',
  PRECHECK: 'precheck',
  GUESS_WIKIDATA: 'guessWikidata',
  FOLLOW_UP_SCOPE_1: 'followUpScope1',
  FOLLOW_UP_SCOPE_2: 'followUpScope2',
  FOLLOW_UP_SCOPE_12: 'followUpScope12',
  FOLLOW_UP_SCOPE_3: 'followUpScope3',
  FOLLOW_UP_BIOGENIC: 'followUpBiogenic',
  FOLLOW_UP_ECONOMY: 'followUpEconomy',
  FOLLOW_UP_GOALS: 'followUpGoals',
  FOLLOW_UP_INITIATIVES: 'followUpInitiatives',
  FOLLOW_UP_FISCAL_YEAR: 'followUpFiscalYear',
  FOLLOW_UP_COMPANY_TAGS: 'followUpCompanyTags',
  FOLLOW_UP_BASE_YEAR: 'followUpBaseYear',
  FOLLOW_UP_INDUSTRY_GICS: 'followUpIndustryGics',
  EXTRACT_DESCRIPTIONS: 'extractDescriptions',
  EXTRACT_EMISSIONS: 'extractEmissions',
  CHECK_DB: 'checkDB',
  DIFF_BASE_YEAR: 'diffBaseYear',
  DIFF_GOALS: 'diffGoals',
  DIFF_INDUSTRY: 'diffIndustry',
  DIFF_INITIATIVES: 'diffInitiatives',
  DIFF_REPORTING_PERIODS: 'diffReportingPeriods',
  DIFF_TAGS: 'diffTags',
  DIFF_DESCRIPTIONS: 'diffDescriptions',
  SAVE_TO_API: 'saveToAPI',
  SEND_COMPANY_LINK: 'sendCompanyLink',
  WIKIPEDIA_UPLOAD: 'wikipediaUpload',
  EXTRACT_LEI: 'extractLEI',
  DIFF_LEI: 'diffLEI',
}

// Create queue clients (NOT workers)
export const queues = {
  parsePdf: new DiscordQueue(QUEUE_NAMES.PARSE_PDF),
  doclingParsePDF: new DiscordQueue(QUEUE_NAMES.DOCLING_PARSE_PDF),
  indexMarkdown: new DiscordQueue(QUEUE_NAMES.INDEX_MARKDOWN),
  nlmExtractTables: new DiscordQueue(QUEUE_NAMES.NLM_EXTRACT_TABLES),
  precheck: new DiscordQueue(QUEUE_NAMES.PRECHECK),
  checkDB: new DiscordQueue(QUEUE_NAMES.CHECK_DB),
  diffBaseYear: new DiscordQueue(QUEUE_NAMES.DIFF_BASE_YEAR),
  diffGoals: new DiscordQueue(QUEUE_NAMES.DIFF_GOALS),
  diffIndustry: new DiscordQueue(QUEUE_NAMES.DIFF_INDUSTRY),
  diffInitiatives: new DiscordQueue(QUEUE_NAMES.DIFF_INITIATIVES),
  diffReportingPeriods: new DiscordQueue(QUEUE_NAMES.DIFF_REPORTING_PERIODS),
  diffDescriptions: new DiscordQueue(QUEUE_NAMES.DIFF_DESCRIPTIONS),
  diffTags: new DiscordQueue(QUEUE_NAMES.DIFF_TAGS),
  extractEmissions: new DiscordQueue(QUEUE_NAMES.EXTRACT_EMISSIONS),
  followUpScope1: new DiscordQueue(QUEUE_NAMES.FOLLOW_UP_SCOPE_1),
  followUpScope2: new DiscordQueue(QUEUE_NAMES.FOLLOW_UP_SCOPE_2),
  followUpScope12: new DiscordQueue(QUEUE_NAMES.FOLLOW_UP_SCOPE_12),
  followUpScope3: new DiscordQueue(QUEUE_NAMES.FOLLOW_UP_SCOPE_3),
  followUpBiogenic: new DiscordQueue(QUEUE_NAMES.FOLLOW_UP_BIOGENIC),
  followUpInitiatives: new DiscordQueue(QUEUE_NAMES.FOLLOW_UP_INITIATIVES),
  followUpCompanyTags: new DiscordQueue(QUEUE_NAMES.FOLLOW_UP_COMPANY_TAGS),
  followUpGoals: new DiscordQueue(QUEUE_NAMES.FOLLOW_UP_GOALS),
  followUpIndustryGics: new DiscordQueue(QUEUE_NAMES.FOLLOW_UP_INDUSTRY_GICS),
  followUpBaseYear: new DiscordQueue(QUEUE_NAMES.FOLLOW_UP_BASE_YEAR),
  followUpEconomy: new DiscordQueue(QUEUE_NAMES.FOLLOW_UP_ECONOMY),
  followUpFiscalYear: new DiscordQueue(QUEUE_NAMES.FOLLOW_UP_FISCAL_YEAR),
  extractDescriptions: new DiscordQueue(QUEUE_NAMES.EXTRACT_DESCRIPTIONS),
  guessWikidata: new DiscordQueue(QUEUE_NAMES.GUESS_WIKIDATA),
  saveToAPI: new DiscordQueue(QUEUE_NAMES.SAVE_TO_API),
  sendCompanyLink: new DiscordQueue(QUEUE_NAMES.SEND_COMPANY_LINK),
  wikipediaUpload: new DiscordQueue(QUEUE_NAMES.WIKIPEDIA_UPLOAD),
  extractLEI: new DiscordQueue(QUEUE_NAMES.EXTRACT_LEI),
  diffLEI: new DiscordQueue(QUEUE_NAMES.DIFF_LEI),
}
