export enum FollowUpType {
  IndustryGics = 'followUp/industryGics',
  Scope1 = 'followUp/scope1',
  Scope2 = 'followUp/scope2',
  Scope12 = 'followUp/scope12',
  Scope3 = 'followUp/scope3',
  Biogenic = 'followUp/biogenic',
  Economy = 'followUp/economy',
  Goals = 'followUp/goals',
  Initiatives = 'followUp/initiatives',
  FiscalYear = 'followUp/fiscalYear',
  CompanyTags = 'followUp/companyTags',
  BaseYear = 'followUp/baseYear',
  Lei = 'extractLEI',
  Wikidata = 'wikidata',
  Precheck = 'precheck',
  ExtractEmissions = 'extractEmissions',
}

export enum JobType {
  IndustryGics = 'followUp/industryGics',
  Scope12 = 'followUp/scope12',
  Scope3 = 'followUp/scope3',
  Biogenic = 'followUp/biogenic',
  Economy = 'followUp/economy',
  Goals = 'followUp/goals',
  Initiatives = 'followUp/initiatives',
  FiscalYear = 'followUp/fiscalYear',
  CompanyTags = 'followUp/companyTags',
  BaseYear = 'followUp/baseYear',
  Lei = 'extractLEI',

  Wikidata = 'wikidata',
  Precheck = 'precheck',
  ExtractEmissions = 'extractEmissions',
}
