apiVersion: apps/v1
kind: Deployment
metadata:
  name: garbo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: garbo
  template:
    metadata:
      labels:
        app: garbo
    spec:
      terminationGracePeriodSeconds: 60
      initContainers:
        - name: db-migration
          image: ghcr.io/klimatbyran/garbo
          command: ['npm', 'run', 'migrate']
          resources:
            requests:
              memory: '64Mi'
              cpu: '100m'
            limits:
              memory: '128Mi'
              cpu: '200m'
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: postgres-password
            - name: DATABASE_URL
              value: postgresql://postgres:$(POSTGRES_PASSWORD)@postgresql:5432/garbo
      containers:
        - image: ghcr.io/klimatbyran/garbo
          resources: {}
          name: garbo
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: env
                  key: NODE_ENV
            - name: DISCORD_APPLICATION_ID
              valueFrom:
                secretKeyRef:
                  name: env
                  key: DISCORD_APPLICATION_ID
            - name: DISCORD_SERVER_ID
              valueFrom:
                secretKeyRef:
                  name: env
                  key: DISCORD_SERVER_ID
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: env
                  key: DISCORD_TOKEN
            - name: DISCORD_CHANNEL_ID
              valueFrom:
                secretKeyRef:
                  name: env
                  key: DISCORD_CHANNEL_ID
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: env
                  key: OPENAI_API_KEY
            - name: OPENAI_ORG_ID
              valueFrom:
                secretKeyRef:
                  name: env
                  key: OPENAI_ORG_ID
            - name: API_TOKENS
              valueFrom:
                secretKeyRef:
                  name: env
                  key: API_TOKENS
            - name: API_BASE_URL
              value: http://garbo/api
            - name: API_PORT
              valueFrom:
                secretKeyRef:
                  name: env
                  key: API_PORT
            - name: OPENAPI_PREFIX
              valueFrom:
                secretKeyRef:
                  name: env
                  key: OPENAPI_PREFIX
            - name: CACHE_MAX_AGE
              valueFrom:
                secretKeyRef:
                  name: env
                  key: CACHE_MAX_AGE
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: postgres-password
            - name: DATABASE_URL
              value: postgresql://postgres:$(POSTGRES_PASSWORD)@postgresql:5432/garbo
            - name: CHROMA_HOST
              valueFrom:
                secretKeyRef:
                  name: env
                  key: CHROMA_HOST
            - name: CHROMA_CHUNK_SIZE
              valueFrom:
                secretKeyRef:
                  name: env
                  key: CHROMA_CHUNK_SIZE
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: env
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: env
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
            - name: DOCLING_URL
              valueFrom:
                secretKeyRef:
                  name: env
                  key: DOCLING_URL
            - name: NLM_INGESTOR_URL
              valueFrom:
                secretKeyRef:
                  name: env
                  key: NLM_INGESTOR_URL
            - name: BERGET_AI_TOKEN
              valueFrom:
                secretKeyRef:
                  name: env
                  key: BERGET_AI_TOKEN
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: env
                  key: GITHUB_CLIENT_ID
            - name: GITHUB_ORG
              valueFrom:
                secretKeyRef:
                  name: env
                  key: GITHUB_ORG
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: env
                  key: GITHUB_CLIENT_SECRET
            - name: GITHUB_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: env
                  key: GITHUB_REDIRECT_URI
            - name: MAILCHIMP_API_KEY
              valueFrom:
                secretKeyRef:
                  name: env
                  key: MAILCHIMP_API_KEY
            - name: MAILCHIMP_SERVER_PREFIX
              valueFrom:
                secretKeyRef:
                  name: env
                  key: MAILCHIMP_SERVER_PREFIX
            - name: MAILCHIMP_LIST_ID
              valueFrom:
                secretKeyRef:
                  name: env
                  key: MAILCHIMP_LIST_ID
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: env
                  key: JWT_SECRET
            - name: JWT_EXPIRES_IN
              valueFrom:
                secretKeyRef:
                  name: env
                  key: JWT_EXPIRES_IN
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: env
                  key: API_SECRET
            - name: FRONTEND_URL
              valueFrom:
                secretKeyRef:
                  name: env
                  key: FRONTEND_URL
            - name: WIKI_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env
                  key: WIKI_PASSWORD
            - name: WIKI_USERNAME
              valueFrom:
                secretKeyRef:
                  name: env
                  key: WIKI_USERNAME
          imagePullPolicy: Always
