apiVersion: apps/v1
kind: Deployment
metadata:
  name: docling
spec:
  selector:
    matchLabels:
      app: docling
  template:
    metadata:
      labels:
        app: docling
    spec:
      containers:
        - image: quay.io/docling-project/docling-serve
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              memory: 4Gi
          name: docling
          ports:
            - containerPort: 5001
          env:
          - name: DOCLING_SERVE_ENABLE_UI
            value: "true"
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: docling
spec:
  ports:
    - port: 5001
      targetPort: 5001
  selector:
    app: docling
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: docling-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: docling
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300 # Wait 5 minutes before scaling down
    scaleUp:
      stabilizationWindowSeconds: 60 # Wait 1 minute before scaling up