apiVersion: apps/v1
kind: Deployment
metadata:
  name: docling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docling
  template:
    metadata:
      labels:
        app: docling
    spec:
      containers:
        - name: docling
          image: quay.io/docling-project/docling-serve
          ports:
            - containerPort: 5001
          env:
            - name: DOCLING_SERVE_ENABLE_UI
              value: 'true'
          readinessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              memory: 4Gi
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: docling
spec:
  selector:
    app: docling
  ports:
    - name: http
      port: 5001
      targetPort: 5001
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: docling-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: docling
  minReplicas: 2
  maxReplicas: 15
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300 # Wait 5 minutes before scaling down
    scaleUp:
      stabilizationWindowSeconds: 60 # Wait 1 minute before scaling up
