apiVersion: apps/v1
kind: Deployment
metadata:
  name: nlm
spec:
  selector:
    matchLabels:
      app: nlm
  template:
    metadata:
      labels:
        app: nlm
    spec:
      containers:
        - image: ghcr.io/nlmatics/nlm-ingestor
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              memory: 4Gi
          name: nlm
          ports:
            - containerPort: 5001
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: nlm
spec:
  ports:
    - port: 5001
      targetPort: 5001
  selector:
    app: nlm
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nlm-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nlm
  minReplicas: 1
  maxReplicas: 15
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
