apiVersion: apps/v1
kind: Deployment
metadata:
  name: nlm
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nlm
  template:
    metadata:
      labels:
        app: nlm
    spec:
      containers:
        - image: ghcr.io/nlmatics/nlm-ingestor
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 256Mi
          name: nlm
          ports:
            - containerPort: 5001
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: nlm
spec:
  ports:
    - port: 5001
      targetPort: 5001
  selector:
    app: nlm
